### ISSUE TITLE
DatabaseService.deleteOne returns HTTP 204

### ISSUE THREAD

**Issue by dchagastelles** [elastos/Elastos.Hive.JS.SDK#24]
when 

_DELETE http://localhost:9001/api/v2/vault/db/collection/works?deleteone=false withAuthorization: true payload: {"filter":{"author":"john doe2"}}_ 

is called, hive node returns HTTP 204, when we are expecting is a json with this structure

_{ "acknowledged": true, "deleted_count": 1 }_

which because of it we have: **ERROR HttpException (057x1zw)  Unexpected end of JSON input Caused by SyntaxError: SyntaxError: Unexpected end of JSON input**

**Comment by carlduranleau** [comment]
Fixed.
